#!/bin/bash
nclude <stdio.h>


/**


 * main - Entry
  : Return 0
  
  
   */
   
   
   main(void)
   
   
   int main(void)
   
   
   {
	   	
	   
	   printf("Size of a char: %i byte(s)\n", sizeof(char));
	   
	   
	   printf("Size of an int: %i byte(s)\n", sizeof(int));
	   
	   
	   printf("Size of a long int: %i byte(s)\n", sizeof(long int));
	   
	   
	   printf("Size of a long long int: %i byte(s)\n", sizof(long long int));
	   
	   
	   printf("Size of a float: %i byte(s)\n", sizof(float));
	   
	   
	   printf("Size of a long long int: %i byte(s)\n", sizeof(long long int));
	   
	   
	   printf("Size of a float: %i byte(s)\n", sizeof(float));
	   
	   
	   return (0);
	   
	   
   }



#include <stdio.h>


#include <unistd.h>       

/**


 * main - Entry
  : Return 1
  
  
   */
   
   
    
   int main(void)
   
   
   {
	   	
	   
	   write(1, "and that piece of art is useful\" - Dora Korpar, 2015-10-19\n", 59);
	   
	   
	   return (1);
	   
	   
   }





0x00. C - Hello, World
0. #!/bin/bash
gcc -E $CFILE -o c

1. #!/bin/bash
gcc -c $CFILE

2. #!/bin/bash
gcc -S $CFILE

3. #!/bin/bash
gcc $CFILE -o cisfun

4. #include <stdio.h>                                                                                                                      
/**                                                                                                                                     
 * main - Entry                                                                                                                         
  * Return: Always 0                                                                                                                     
   */                                                                                                                                     
   int main(void)                                                                                                                          
   {                                                                                                                                       
	           puts("\"Programming is like building a multi lingual puzzle);                                                            
		           return (0);
		   }
	   
	   5. #include <stdio.h>                                                                                                                      
	   /**                                                                                                                                     
	    * main - Entry                                                                                                                         
	     * Return: Always 0                                                                                                                     
	      */ 
	      int main(void)
	      {
		      	printf("with proper grammar, but the outcome is a piece of art,\n");
				return (0);
			}
		
		6. #include <stdio.h>                                                                                                                      
		/** 
		 * main - Entry
		  * Return: Always 0
		   */
		   main(void)
		   int main(void)
		   {
			   	printf("Size of a char: %i byte(s)\n", sizeof(char));
					printf("Size of an int: %i byte(s)\n", sizeof(int));
						printf("Size of a long int: %i byte(s)\n", sizeof(long int));
							printf("Size of a long long int: %i byte(s)\n", sizof(long long int));
								printf("Size of a float: %i byte(s)\n", sizof(float));
									printf("Size of a long long int: %i byte(s)\n", sizeof(long long int));
										printf("Size of a float: %i byte(s)\n", sizeof(float));
											return (0);
										}
									
									Advance task
									
									7. #!/bin/bash
									gcc -S -masm=intel $CFILE
									
									8.  #include <stdio.h>
									    #include <unistd.h>                                                                                                                      
									    /** 
									     * main - Entry
									      * Return: Always 1
									      */
									      int main(void)
									      {
										      	write(1, "and that piece of art is useful\" - Dora Korpar, 2015-10-19\n", 59);
												return (1);
											}
										
										NB:
										Always remember to check your code with:  betty <filename>  to confirm if there is error in your codear
										gcc -E $CFILE -o c
